### ISSUE TITLE
install.sh -m full / error 

### ISSUE THREAD

**Issue by imsourceboom** [ton-blockchain/mytonctrl#103]
There is a problem with 'wget https://raw.githubusercontent.com/ton-blockchain/mytonctrl/master/scripts/install.sh' .
I ran it in full mode.

OS - Ubuntu 18.04.6
Account - root, user both

Errors like this keep appearing.

<img width="622" alt="Screen Shot 2022-07-19 at 1 09 13" src="https://user-images.githubusercontent.com/24690213/179566697-b2e2c613-6556-494e-bc38-7bb614b34bb8.png">

**Comment by awesome-doge** [comment]
> There is a problem with 'wget https://raw.githubusercontent.com/ton-blockchain/mytonctrl/master/scripts/install.sh' . I ran it in full mode.
> 
> OS - Ubuntu 18.04.6 Account - root, user both
> 
> Errors like this keep appearing.
> 
> <img alt="Screen Shot 2022-07-19 at 1 09 13" width="622" src="https://user-images.githubusercontent.com/24690213/179566697-b2e2c613-6556-494e-bc38-7bb614b34bb8.png">



This problem should not exist now.

* Actually `test-storage` does not need to be compiled.
* In past code changes, compiling `test-storage` has been removed.

references
https://github.com/ton-blockchain/mytonctrl/blob/f168bb065abc877a6b4ba5153a7e7db86ae904aa/scripts/toninstaller.sh#L138

**Comment by igroman787** [comment]
This issue was fixed by this commit: https://github.com/ton-blockchain/mytonctrl/commit/11e9bde1efc039bddb9bc368629c55ba96169f4e
