### ISSUE TITLE
The process is already running

### ISSUE THREAD

**Issue by ex3ndr** [ton-blockchain/mytonctrl#117]
Quite often when i re-connect via SSH i get this error. How easily this could be fixed?

**Comment by aandrewww** [comment]
You can check active ssh sessions 
`pstree -p`

the output will look something like this:
```
├─sshd(3050)─┬─sshd(7577)───bash(7633)───bash(7867)───python3(7868)─┬─{python3}(7873)
│            │                                                      ├─{python3}(7874)
│            │                                                      └─{python3}(7875)
│            └─sshd(13136)───bash(13192)───pstree(13212)
```

and then kill the idle ssh session, type:
`kill 7577`

**Comment by awesome-doge** [comment]
> Quite often when i re-connect via SSH i get this error. How easily this could be fixed?

Dear developers, this command will be very useful.
```
pkill -f 'mytonctrl.py'
```

If you don't have pkill you can install it.
