### ISSUE TITLE
some troubles

### ISSUE THREAD

**Issue by Mourrit** [ton-blockchain/mytonctrl#30]
(sorry for my not perfect English)

I had some troubles using mytonctrl utility.

I use Fedora Linux and mytonctrl is not supported for my OS, so first I tried to install mytonctrl into Debian official Docker container (latest tag). 

In the official Debian Docker container by default not installed some packages as "wget" and "systemd" ("systemd" is needed to run "systemctl" command). "wget" is easy to install, but install and customize "systemd" is a bit difficult. 

So then mytonctrl is not simple one-script install in this way.

In the installation process raised such exception. 

> [100%] Built target json2tlo
> Scanning dependencies of target http-proxy
> [100%] Building CXX object http/CMakeFiles/http-proxy.dir/http-proxy.cpp.o
> [100%] Linking CXX executable http-proxy
> [100%] Built target http-proxy
> Scanning dependencies of target rldp-http-proxy
> [100%] Building CXX object rldp-http-proxy/CMakeFiles/rldp-http-proxy.dir/rldp-http-proxy.cpp.o
> [100%] Linking CXX executable rldp-http-proxy
> [100%] Built target rldp-http-proxy
> [6/6] TON software installation complete
> [3/4] Launching the mytoninstaller.py
> [debug]   15.06.2021, 15:02:06.585 (UTC)  <Logging>     Start WritingLogFile thread.
> [debug]   15.06.2021, 15:02:06.586 (UTC)  <SelfTesting> Start SelfTesting thread.
> [info]    15.06.2021, 15:02:06.586 (UTC)  <MainThread>  Start program '/usr/src/mytonctrl/mytoninstaller.py'
> [debug]   15.06.2021, 15:02:06.586 (UTC)  <MainThread>  start FirstMytoncoreSettings fuction
> Traceback (most recent call last):
>   File "/usr/src/mytonctrl/mytoninstaller.py", line 535, in <module>
>     General()
>   File "/usr/src/mytonctrl/mytoninstaller.py", line 118, in General
>     FirstMytoncoreSettings()
>   File "/usr/src/mytonctrl/mytoninstaller.py", line 202, in FirstMytoncoreSettings
>     Add2Systemd(name="mytoncore", user=user, start="/usr/bin/python3 /usr/src/mytonctrl/mytoncore.py")
>   File "/usr/src/mytonctrl/mypylib/mypylib.py", line 951, in Add2Systemd
>     subprocess.run(args)
>   File "/usr/lib/python3.7/subprocess.py", line 472, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'systemctl': 'systemctl'
> root@11bc55ae6036:~# 
> 

On the third try I got:

> "[4/4] Mytonctrl installation completed"

After installation, I got some problems.

![image](https://user-images.githubusercontent.com/46128538/122587727-db55b180-d066-11eb-8eba-8f6bfd82f280.png)

![image](https://user-images.githubusercontent.com/46128538/122588066-4ef7be80-d067-11eb-8c72-d3e8146ef9c2.png)

In the official Ubuntu Docker container (ubuntu:20.04) situation is the same as in the official Debian Docker container.

Then I tried to use mytonctrl in Debian (10.9.0) via VirtualBox.

![image](https://user-images.githubusercontent.com/46128538/122589042-7733ed00-d068-11eb-9484-9ebd67b8602f.png)

And then I tried to use mytonctrl in Ubuntu (20.04.2.0) via VirtualBox.

![image](https://user-images.githubusercontent.com/46128538/122589575-19ec6b80-d069-11eb-9c5a-04f9f9c248d1.png)

If you need additional information you can write me on Telegram: https://t.me/mourrit.

**Comment by igroman787** [comment]
Bug `float division by zero` fixed by this commit: https://github.com/igroman787/mytonctrl/commit/33fde920080cfc9f77635456539644733ed32578

The `WaitTransaction error: time out` error occurs due to a long processing of the request by the LiteServer. Mytonctrl waits 30 seconds and gives an error, although the transaction can be completed in 31 seconds. In general, this error can be ignored if funds have been successfully received after a certain time. But maybe LiteServer dropped your transfer request due to its high workload - then you will have to repeat the request for sending coins. But this is rare. I am going to add a function to select the best LiteServer to mytonctrl shortly.

**Comment by igroman787** [comment]
Due to the peculiarity of work, mytonctrl uses systemd, and therefore cannot be used inside docker. Maybe someone will fix this in the future. But so far mytonctrl is not friendly with docker.

**Comment by awesome-doge** [comment]
> Due to the peculiarity of work, mytonctrl uses systemd, and therefore cannot be used inside docker. Maybe someone will fix this in the future. But so far mytonctrl is not friendly with docker.

About systemd in docker
Install sudo apt-get install systemd in the docker environment to install it smoothly.
But when the docker container is restarted, systemd will not work.
We must restart these systemd services manually.
