### ISSUE TITLE
pool management commands are missing in v2

### ISSUE THREAD

**Issue by ingria** [ton-blockchain/mytonctrl#328]
`pools_list` and `withdraw_from_pool` commands are missing in the latest version of mytonctrl

pool credentials are present in the local directory:

~$ ls /home/ton/.local/share/mytoncore/pools/
p1.addr  p2.addr

**Comment by yungwine** [comment]
Enable `nominator-pool` mode:
```
MyTonCtrl> enable_mode nominator-pool
```

**Comment by ingria** [comment]
that helped, thanks
