### ISSUE TITLE
[Ubuntu] stops before compilation

### ISSUE THREAD

**Issue by kesha-antonov** [ton-blockchain/mytonctrl#34]
Hi!

Script stops  on this step https://github.com/igroman787/mytonctrl/blob/393e07c777d3ecbcd2b64443ea271f99635ec7bf/scripts/toninstaller.sh#L107

**Comment by kesha-antonov** [comment]
Ok, it now works.

But after installation I have error

```
$ mytonctrl
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 9, in <module>
    local = MyPyClass(__file__)
  File "/usr/src/mytonctrl/mypylib/mypylib.py", line 161, in __init__
    self.Refresh()
  File "/usr/src/mytonctrl/mypylib/mypylib.py", line 179, in Refresh
    os.makedirs(self.buffer[_myWorkDir], exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/.local/share/mytonctrl/'
```

**Comment by kr4t0z** [comment]
Did you installed and runned it as Sudo User?

**Comment by igroman787** [comment]
Yes, this problem occurs if the user did not have a `/.local/share/` folder.
MyTonCtrl creates this folder, but forgets to change the rights of this folder.
Soon I will solve this problem inside mtc.
However, right now you can change the rights to this folder yourself:
`chown -R ubuntu:ubuntu /home/ubuntu/.local/`

**Comment by kesha-antonov** [comment]
> Yes, this problem occurs if the user did not have a `/.local/share/` folder.
> MyTonCtrl creates this folder, but forgets to change the rights of this folder.
> Soon I will solve this problem inside mtc.
> However, right now you can change the rights to this folder yourself:
> `chown -R ubuntu:ubuntu /home/ubuntu/.local/`

Thanks

**Comment by exhang** [comment]
> Ok, it now works.
> 
> But after installation I have error
> 
> ```
> $ mytonctrl
> Traceback (most recent call last):
>   File "/usr/src/mytonctrl/mytonctrl.py", line 9, in <module>
>     local = MyPyClass(__file__)
>   File "/usr/src/mytonctrl/mypylib/mypylib.py", line 161, in __init__
>     self.Refresh()
>   File "/usr/src/mytonctrl/mypylib/mypylib.py", line 179, in Refresh
>     os.makedirs(self.buffer[_myWorkDir], exist_ok=True)
>   File "/usr/lib/python3.8/os.py", line 223, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/home/ubuntu/.local/share/mytonctrl/'
> ```



> Ok, it now works.
> 
> But after installation I have error
> 
> ```
> $ mytonctrl
> Traceback (most recent call last):
>   File "/usr/src/mytonctrl/mytonctrl.py", line 9, in <module>
>     local = MyPyClass(__file__)
>   File "/usr/src/mytonctrl/mypylib/mypylib.py", line 161, in __init__
>     self.Refresh()
>   File "/usr/src/mytonctrl/mypylib/mypylib.py", line 179, in Refresh
>     os.makedirs(self.buffer[_myWorkDir], exist_ok=True)
>   File "/usr/lib/python3.8/os.py", line 223, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/home/ubuntu/.local/share/mytonctrl/'
> ```

how did you solve the problem stops before compiling?

**Comment by grifits** [comment]
> > Да, эта проблема возникает, если у пользователя не было `/.local/share/`папки. 
> > MyTonCtrl создает эту папку, но забывает изменить права этой папки. 
> > Скоро решу эту проблему внутри mtc. 
> > Однако прямо сейчас вы можете самостоятельно изменить права на эту папку:
> > `chown -R ubuntu:ubuntu /home/ubuntu/.local/`
> 
> Спасибо

Здравствуйте, вам удалось решить проблему остановки перед компиляцией?

**Comment by igroman787** [comment]
This issue has been fixed by the commit: https://github.com/ton-blockchain/mytonctrl/commit/84f1aaee32282636d87e251813b78566133e9e57
