### ISSUE TITLE
How to add comment to "mg" command?

### ISSUE THREAD

**Issue by n0mer** [ton-blockchain/mytonctrl#47]
Exmo exchange requires "invoice" in order to make deposit. As far as i understand they have single outbound address, and then process txns by "invoice"

Can you please tell how to specify comment in "mg" tonctrl command while sending tokens?

![image](https://user-images.githubusercontent.com/1862997/133936719-7b08053e-8134-405b-975a-efaaaae203a1.png)

Thanks

**Comment by igroman787** [comment]
You can add a comment using the `-C` flag.
Example: `mg wallet_001 EQABMMdzRuntgt9nfRB61qd1wR-cGPagXA3ReQazVYUNrT7p 123 -С 123456789`
