### ISSUE TITLE
Disable Telemetry by default

### ISSUE THREAD

**Issue by ex3ndr** [ton-blockchain/mytonctrl#48]
It turns out that mytonctrl sends telemetry by default without asking. TON is have built in anonymization and this effectively negates it.

**Comment by igroman787** [comment]
Yes, it is written about it in `README.md` section `Functional`: https://github.com/igroman787/mytonctrl/blame/master/README.md#L44

By default, `mytonctrl` sends validator statistics to the server https://toncenter.com
This is necessary to identify anomalies in the network, as well as to quickly respond to developers.

The following data is sent:
1. adnl
2. validator status (is process is running, unixtime, masterchainblocktime)
3. cpu number
4. cpu load average
5. network load average
6. transactions per second (TPS)
7. used version of repositories
8. stake (if assigned)

To disable telemetry during installation, use the `-t` flag:
```sh
sudo bash install.sh -m <mode> -t
```

To disable telemetry after installation:
```sh
MyTonCtrl> set sendTelemetry false
```
