### ISSUE TITLE
Stop installing on stage 4/6

### ISSUE THREAD

**Issue by i0xHeX** [ton-blockchain/mytonctrl#53]
Running commands:
```
wget https://raw.githubusercontent.com/igroman787/mytonctrl/master/scripts/install.sh
sudo bash install.sh -m lite
```

Stops on stage 4:
![image](https://user-images.githubusercontent.com/33582973/141285181-040e5b62-7427-4b6f-a7ac-927279d8f0c3.png)

**Comment by stre4m** [comment]
Same issue =(

**Comment by Profesor08** [comment]
Edit `toninstaller.sh` and replace `MemAvailable` with `MemFree`. Correct replacement you can find there: `cat /proc/meminfo`

**Comment by grifits** [comment]
> toninstaller.sh у меня этот файл находится /usr/src/ton/mytonctrl/scrept, после его правки я снова запускаю sudo bash install.sh -m lite и все сначала. То есть скрипт install вытаскивает из ГИТ исходный файл toninstaller.sh и перезаписывает исправленный мной. Подскажите что делаю не так или как исправить. Спасибо

**Comment by Profesor08** [comment]
> > toninstaller.sh 
Скрипт не кроссплатформенный.  Просто посмотри как у тебя называется параметр и поправь его в скрипе. Потом запусти сам скрипт. Да, чуть больше телодвижений, но все заработает, установится и запустится.

**Comment by grifits** [comment]
> cat /proc/meminfo

Спасибо вам за ответ.
Я отредактировал как вы указали выше, запускал сам скрипт и к сожалению ничего не меняется.
Будьте добры объясните пожалуйста подробнее, какой параметр мне нужно изменить в скрипте.
P.S. MemAvailable на MemFree изменил. Вот скрин cat /proc/meminfo
![Снимок экрана от 2022-01-02 06-55-33](https://user-images.githubusercontent.com/35652411/147865738-51159c87-ea23-44e8-a03c-61259cd559be.png)
![Снимок экрана от 2022-01-02 06-55-51](https://user-images.githubusercontent.com/35652411/147865740-adce3008-b84a-4215-88c7-ac975f9dc613.png)

**Comment by grifits** [comment]
> 
Вот изменения в скрипте
![Снимок экрана от 2022-01-02 06-58-41](https://user-images.githubusercontent.com/35652411/147865776-a4d638af-4392-4ba7-b719-2c7d7d178421.png)

**Comment by grifits** [comment]
> > 
> 
> Вот изменения в скрипте ![Снимок экрана от 2022-01-02 06-58-41](https://user-images.githubusercontent.com/35652411/147865776-a4d638af-4392-4ba7-b719-2c7d7d178421.png)

Возможно необходимо объяснить: я очень далек от программирования и написания чего-либо, мои познания заканчиваются на: изменить строку А на строку В.

**Comment by grifits** [comment]
> > > toninstaller.sh 
> > > Скрипт не кроссплатформенный. Просто посмотри как у тебя параметр и поправь его в скрипе. Потом запусти сам скрипт. Да, чуть больше телодвижений, но все заработает, установится и запустится.

Возможно необходимо объяснить: я очень далек от программирования и написания чего-либо, мои познания заканчиваются на: изменить строку А на строку В.

**Comment by grifits** [comment]
Has anyone been able to resolve this issue?

**Comment by grifits** [comment]
stopping the execution of the script occurs at this line: **let "cpuNumber = memory / 2100000"**
after replacing line **MemAvailable** with **MemFree**, I did **echo memory**, I get a constantly different result, approximately equal to 170 000
based on the above, **cpuNumber** should contain 0.081 (170000/2100000).
who knows what **cpuNumber** is for a variable, what data it should contain?
perhaps the solution is associated with the figure 2100000, also the question of what this figure means
or what other value should be supplied instead....

**Comment by udav-rus** [comment]
Проблема в малом количестве памяти. Не менее 8 Гб должно быть.

**Comment by kosyachniy** [comment]
I have decided it after reading script: https://github.com/igroman787/mytonctrl/blob/master/scripts/toninstaller.sh

You need more RAM (it is minimum: **4Gb RAM** & 2 CPU)

**Comment by udav-rus** [comment]
> I have decided it after reading script: https://github.com/igroman787/mytonctrl/blob/master/scripts/toninstaller.sh
> 
> You need more RAM (it is minimum: **4Gb RAM** & 2 CPU)

U r wrong, imho. I try 2 install in series on 2GB to 8GB RAM. I pass step 4 only after 8G RAM installed on PC.
