### ISSUE TITLE
Installation fails after rocksdb

### ISSUE THREAD

**Issue by viktorprogger** [ton-blockchain/mytonctrl#54]
I have no idea on what's wrong or not installed. The error is not descriptive :(
![image](https://user-images.githubusercontent.com/7670669/141493830-e134baad-af6f-4d63-bffb-7edcb463d682.png)

**Comment by Avendattor** [comment]
Same issue on Pop!_OS 21.10 (Based on Ubuntu).

**Comment by jetaweb** [comment]
got the same error(

`[ 55%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/third-party/folly/folly/synchronization/WaitOptions.cpp.o
[ 55%] Linking CXX static library librocksdb.a
[ 55%] Built target rocksdb
make[1]: *** [CMakeFiles/Makefile2:7077: crypto/CMakeFiles/fift.dir/rule] Error 2
make: *** [Makefile:1882: fift] Error 2`

**Comment by awesome-doge** [comment]
This issue should have been resolved.
https://github.com/ton-blockchain/ton/pull/349/commits/64615a9766525191b1c825a1098482ad424274df

The issue should be closed @igroman787
