### ISSUE TITLE
error: 'NoneType' object has no attribute 'GetValidatorStatus'

### ISSUE THREAD

**Issue by DeathAdd1r** [ton-blockchain/mytonctrl#55]
![Снимок экрана от 2021-11-14 01-23-38](https://user-images.githubusercontent.com/94260152/141661872-520b4b7f-ff13-47b8-94ed-ba3ad84e2eb6.png)
Please help me, i really can't understand what i needed to do

**Comment by ntohidi** [comment]
I have the same problem!

**Comment by ssi91** [comment]
Hey! Seems like it's related to https://github.com/ton-blockchain/mytonctrl/issues/35

**Comment by igroman787** [comment]
Solution: https://github.com/ton-blockchain/mytonctrl/issues/35#issuecomment-894018696
