### ISSUE TITLE
Lite Server setup  [Error : 500 : LITE_SERVER_NETWORKadnl query timeout]

### ISSUE THREAD

**Issue by ermenagildo** [ton-blockchain/mytonctrl#58]
### Hello. I did set up a new Lite Server 2 days ago.
Steps:
sudo bash install.sh -m full
share UPD port
share TCP port liteserves from exported config
-----
 mytonctrl>>installer>>status
Full node status: True
Mytoncore status: True
V.console status: True
Liteserver status: True
-----

Tested configured Lite Server at PC under windows 10 with miner
https://github.com/tontechio/pow-miner-gpu/releases
logs:
.........
```
[ 1][t 1][2021-11-19 11:17:58.8434486][tonlib-cli.cpp:907][!console]	[Error : 500 : LITE_SERVER_NETWORKadnl query timeout]
[ 1][t 2][2021-11-19 11:17:58.8439667][tonlib-cli.cpp:755][!PowMiner]	pminer: [Error : 500 : LITE_SERVER_NETWORKadnl query timeout] (#576212490)
```
.........

May I fix that?

Thanks for patient

**Comment by igroman787** [comment]
More data is needed to solve your problem.
There is a small chance that you are using public nodes and not your own. To use your node, use command `mytonctrl -> installer -> clcf` and feed the new config `/usr/bin/ton/local.config.json` to the end program.
If you are sure that you are using your node, then you need to look at the node logs: `tail -f /var/ton-work/log.thread*`. Also, make sure that your node has enough resources (processor, memory, free disk space)

**Comment by igroman787** [comment]
Since mining is over, I think this issue should be closed
