### ISSUE TITLE
Как сделать, чтобы валидатор заработал?

### ISSUE THREAD

**Issue by Grohotun** [ton-blockchain/mytonctrl#59]
Ton на кошельке валидатора есть, какие команды надо выполнить для участия в elections и дальнейшего процесса?
Кошелек активирован, база давно синхронизирована.

**Comment by jetaweb** [comment]
Закинуть на кошелёк валидатора 600к+ монет.

**Comment by Grohotun** [comment]
Так stake написано 10к минимум

**Comment by igroman787** [comment]
Clean validation requires more than 600k coins
