### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'systemctl'

### ISSUE THREAD

**Issue by mfarahy** [ton-blockchain/mytonctrl#62]
Commands:
`
                          wget https://raw.githubusercontent.com/igroman787/mytonctrl/master/scripts/install.sh 
                          sudo bash install.sh -m full
 `
OS
`NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal`

Error Log:

`[6/6] TON software installation complete
[3/4] Launching the mytoninstaller.py
[debug]   24.12.2021, 07:39:09.915 (UTC)  <Logging>     Start WritingLogFile thread.
[debug]   24.12.2021, 07:39:09.916 (UTC)  <SelfTesting> Start SelfTesting thread.
[info]    24.12.2021, 07:39:09.916 (UTC)  <MainThread>  Start program '/usr/src/mytonctrl/mytoninstaller.py'
[debug]   24.12.2021, 07:39:09.916 (UTC)  <MainThread>  start FirstMytoncoreSettings fuction
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytoninstaller.py", line 956, in <module>
    General()
  File "/usr/src/mytonctrl/mytoninstaller.py", line 218, in General
    FirstMytoncoreSettings()
  File "/usr/src/mytonctrl/mytoninstaller.py", line 298, in FirstMytoncoreSettings
    Add2Systemd(name="mytoncore", user=user, start="/usr/bin/python3 /usr/src/mytonctrl/mytoncore.py")
  File "/usr/src/mytonctrl/mypylib/mypylib.py", line 911, in Add2Systemd
    subprocess.run(args)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'systemctl'`

**Comment by mfarahy** [comment]
same result for 

`NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal`

**Comment by mfarahy** [comment]
same result in debian 10

`root@150189f1205a:/# cat etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

**Comment by awesome-doge** [comment]
> Commands: `wget https://raw.githubusercontent.com/igroman787/mytonctrl/master/scripts/install.sh sudo bash install.sh -m full` OS `NAME="Ubuntu" VERSION="20.04.3 LTS (Focal Fossa)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 20.04.3 LTS" VERSION_ID="20.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=focal UBUNTU_CODENAME=focal`
> 
> Error Log:
> 
> `[6/6] TON software installation complete [3/4] Launching the mytoninstaller.py [debug] 24.12.2021, 07:39:09.915 (UTC) <Logging> Start WritingLogFile thread. [debug] 24.12.2021, 07:39:09.916 (UTC) <SelfTesting> Start SelfTesting thread. [info] 24.12.2021, 07:39:09.916 (UTC) <MainThread> Start program '/usr/src/mytonctrl/mytoninstaller.py' [debug] 24.12.2021, 07:39:09.916 (UTC) <MainThread> start FirstMytoncoreSettings fuction Traceback (most recent call last): File "/usr/src/mytonctrl/mytoninstaller.py", line 956, in <module> General() File "/usr/src/mytonctrl/mytoninstaller.py", line 218, in General FirstMytoncoreSettings() File "/usr/src/mytonctrl/mytoninstaller.py", line 298, in FirstMytoncoreSettings Add2Systemd(name="mytoncore", user=user, start="/usr/bin/python3 /usr/src/mytonctrl/mytoncore.py") File "/usr/src/mytonctrl/mypylib/mypylib.py", line 911, in Add2Systemd subprocess.run(args) File "/usr/lib/python3.8/subprocess.py", line 493, in run with Popen(*popenargs, **kwargs) as process: File "/usr/lib/python3.8/subprocess.py", line 858, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'systemctl'`

I had the same problem before.
I was in a docker environment before.

Regarding `[Errno 2] No such file or directory: 'systemctl'`
You can try:
````
sudo apt-get install systemd

wget https://raw.githubusercontent.com/ton-blockchain/mytonctrl/master/scripts/install.sh
sudo bash install.sh -m <mode>
````

**Comment by igroman787** [comment]
Apparently your system does not have standard components, installing them should solve the problem. The command to install them is in the post above.
