### ISSUE TITLE
can't compile 

### ISSUE THREAD

**Issue by GMX23RUS** [ton-blockchain/mytonctrl#63]
Trying to compile on Ubuntu 20.04.3 LTS usin install.sh:

`[  2%] Linking CXX static library libabsl_time_zone.a
[  2%] Built target absl_time_zone
make[1]: *** [CMakeFiles/Makefile2:7999: crypto/CMakeFiles/fift.dir/rule] Error 2
make: *** [Makefile:2034: fift] Error 2
`
Have no idea, what's wrong.

**Comment by ostapkrus** [comment]
Same issue here. Tried compiling in both full & lite modes on M1 Pro Max. Anybody ran into this Error before and know how to fix?
Thanks

**Comment by awesome-doge** [comment]
> Same issue here. Tried compiling in both full & lite modes on M1 Pro Max. Anybody ran into this Error before and know how to fix? Thanks

https://github.com/ton-blockchain/mytonctrl/pull/97

**Comment by igroman787** [comment]
Should be fixed by this commit: https://github.com/ton-blockchain/mytonctrl/commit/995a36cbf3e4a53c15e0523cf7ba80280a135592
