### ISSUE TITLE
Error: [Errno 2] No such file or directory: '##ADJUST_TO_YOUR_SYSTEM##/bin/lite-client': '##ADJUST_TO_YOUR_SYSTEM##/bin/lite-client'

### ISSUE THREAD

**Issue by gitcoinkuang** [ton-blockchain/mytonctrl#68]
Error: [Errno 2] No such file or directory: '##ADJUST_TO_YOUR_SYSTEM##/bin/lite-client': '##ADJUST_TO_YOUR_SYSTEM##/bin/lite-client'

How can I solve this?

**Comment by igroman787** [comment]
More data needed. What causes this error?
