### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by dankonig** [ton-blockchain/mytonctrl#69]
Thought it might be as easy as sudo apt-get --purge remove mytoncontrol but no such luck. Can I get some help rolling the installation back?

**Comment by awesome-doge** [comment]
If you need to uninstall this can be done
```bash
wget https://raw.githubusercontent.com/ton-blockchain/mytonctrl/master/scripts/uninstall.sh
sudo bash uninstall.sh
````

The issue should be closed @igroman787
