### ISSUE TITLE
pytonv3 not working

### ISSUE THREAD

**Issue by tvorogme** [ton-blockchain/mytonctrl#70]
![image](https://user-images.githubusercontent.com/19264196/148620544-dbe3b073-f549-4980-9aea-e5d94b13b1d1.png)

If you don't run pytonv3 in project (pytonv3 project) root - it doesn't work.
By default systemd service created by mytoncrtl is not specify pytonv3 root.

I have tested on:
Ubuntu 18.04 / latest arch linux

**Comment by tvorogme** [comment]
Ok, I made fixes. Please double-check them :)

**Comment by awesome-doge** [comment]
@tvorogme Has this issue been resolved?

**Comment by igroman787** [comment]
fix: https://github.com/ton-blockchain/mytonctrl/commit/c136b6a3750d087884a33907598b6d6bdb984667
