### ISSUE TITLE
I would like to ask you about ton-coin Validators.

### ISSUE THREAD

**Issue by jini7903kr** [ton-blockchain/mytonctrl#75]
I would like to ask you about ton-coin Validators. Mytonctrl was executed. I checked the available menu through the help menu. I activated my wallet.
Is there any more detailed manual to proceed with Validator? I ask for your help.

**Comment by jetaweb** [comment]
you have to add 350k+ toncoin to validator_wallet and wait for next election period

**Comment by awesome-doge** [comment]
Here https://github.com/ton-blockchain/mytonctrl/blob/master/docs/en/manual-ubuntu.md has commands for setting the stake. You can use the `set stake` command.

The issue should be closed @igroman787

**Comment by cyrusthegreat3421** [comment]
Можно ли стать валидатором арендовав удаленный сервер за 10К ТОН и добавив Номинатора ещё за 10К. И в чем будет отличие если имеешь стэйк Номинатора 360000 и 10000 ТОН?

**Comment by cyrusthegreat3421** [comment]
Насколько я знаю можно арендовать сервер за 10К ТОН
