### ISSUE TITLE
Run mytonctrl in testnet

### ISSUE THREAD

**Issue by Macht59** [ton-blockchain/mytonctrl#76]
Initially I've installed mytonctrl and it ran perfectly. Synchronization completed and my validator was up to date.
Then I decided to test my validator machine before running it on mainnet.
I uninstalled existing installation with uninstall.sh script, modified install.sh so it uses testnet config and performed the installation again. Installation passed without any errors. I can see that validators database is 5.51 Gb, but validator doesn’t syncs.

Did anyone had such problem?

**Comment by Macht59** [comment]
I've removed all liteservers and static_nodes that is down from global.config.json - no reaction.
I've requested 10 coins from @testgiver_ton_bot yesterday and still didn't get them.

Is testnet down?

**Comment by Macht59** [comment]
So I left behind the idea of testing validator on testnet and uninstalled mytonctrl tool with uninstall.sh and installed mainnet mytonctrl with original install.sh script.
Guess what? It doesn't sync ether... 
Now I have the same situation as I had on testnet installation of mytonctrl.

**Comment by awesome-doge** [comment]
This problem, I think, is mainly because there are too few nodes and it is difficult to find the initial block.
Here https://dump.ton.org/ can quickly find the backup of testnet.

The issue should be closed @igroman787
