### ISSUE TITLE
Добавите  описание как удалить это с компьютера. 

### ISSUE THREAD

**Issue by mx-yah** [ton-blockchain/mytonctrl#77]
Добавите  описание как удалить это с компьютера. 
unintall, deinstall

**Comment by Macht59** [comment]
Описано здесь:
https://github.com/igroman787/mytonctrl/blob/69f0c57d4797db0621ab2f0b24af0420a427aeed/docs/ru/FAQ.txt
```
Как удалить mytonctrl?

Запустить от имени администратора скрипт:
`sudo bash /usr/src/mytonctrl/scripts/uninstall.sh`
```
