### ISSUE TITLE
[solved]Local db is not syncing 

### ISSUE THREAD

**Issue by jetaweb** [ton-blockchain/mytonctrl#79]
Hi,

Everything is seems to be ok - validator process work, network traffic work, but local db is still not syncing yet (few days) and sync time increasing =(

any advice, please?

Network load average (Mbit/s): 16.06, 16.89, 18.29
Disks load average (MB/s):  sda:[0.01, 0.13%], sdb:[0.0, 0.0%]
Mytoncore status: working
Local validator status: working
Local validator out of sync: 1646046619 s
Local validator database size: 4.87 Gb

**Comment by jetaweb** [comment]
Problem solved after 3rd reinstall.

**Comment by AcidBurnSB** [comment]
> 

same problem, you uninstall and install again or just use install.sh again?

**Comment by joslee7410** [comment]
I also met this problem, feel it keep saying `out of sync`.
Anyone know how actual to install the full node? Might share with us. thank you so much.

**Comment by awesome-doge** [comment]
You can refer to this link Quick Sync
https://dump.ton.org/

The issue should be closed @igroman787
