### ISSUE TITLE
импортировать кошелек

### ISSUE THREAD

**Issue by gutkati** [ton-blockchain/mytonctrl#80]
Не могу импортировать кошелек. Сделала - сохранить адрес кошелька, удалил его в mytonctrl, а импортировать назад не получается. Что я делаю не так? При этом в конце получился баг - дальше не стирается ( и так получается довольно часто)
![ton](https://user-images.githubusercontent.com/94618780/156167359-29ad6dc2-38b3-40e8-ae00-6be707a3a276.JPG)
.

**Comment by jetaweb** [comment]
Используйте приватный ключ - .local/share/mytoncore/wallets/
