### ISSUE TITLE
Чтение команд из ARGV

### ISSUE THREAD

**Issue by mimikadze** [ton-blockchain/mytonctrl#85]
Добрый день. Было бы супер удобно передавать команды через параметры запуска утилиты.  Например: `mytonctr nw` и получить в STDOUT хотя бы такой же вывод как в интерактивном режиме.

```
Name        Workchain  Address
wallet_003  0          UQC1kGd6JNN_Nasdnjkh8wZ1nw5-hs0tB7Aq_MUOwl-r9fzqbdI
```

Тогда сторонние приложения смогут относительно просто использовать все возможности тулзы (своего рода АПИ). Сейчас большая проблема использовать функции кошелька Ton сторонними приложениями, написанными на стеке где еще нет поддержки сообщества (как в JS, например)

**Comment by igroman787** [comment]
To solve your problem, you can use the built-in capabilities of the linux console. For example, to pass the `status` command and display the status:
`echo status | mytonctrl`
