### ISSUE TITLE
Full node sync issue

### ISSUE THREAD

**Issue by joslee7410** [ton-blockchain/mytonctrl#89]
I have follow the guide and installed.

But I wait for around 1 hours and print the status

```
Load average[8]: 0.31, 0.42, 0.74
Network load average (Mbit/s): 18.52, 22.83, 0.0
Disks load average (MB/s): vda:[0.03, 0.46%]
Mytoncore status: working
Local validator status: working
Local validator out of sync: 1650426946 s
Local validator database size: 0.02 Gb
```

Anyone know how to boost up the sync speed?

Thank you.

**Comment by Deformer** [comment]
+1
i have the same behaviour

**Comment by joslee7410** [comment]
I don't know how the others can proceed so smoothly, might be some place we didn't configure properly :(

**Comment by awesome-doge** [comment]
For fast synchronization of nodes:
You can refer to this link https://dump.ton.org/

**Comment by igroman787** [comment]
To synchronize one hour is not enough. You have to wait about a day.
Perhaps the installation will help you by downloading the dump from the central server dump.ton.org:
`sudo bash install.sh -m full -d`
