### ISSUE TITLE
Ubuntu 22.04 support

### ISSUE THREAD

**Issue by ingria** [ton-blockchain/mytonctrl#90]
Currently ton installer fails with this error:

```
[ 55%] Linking CXX static library librocksdb.a
[ 55%] Built target rocksdb
make[1]: *** [CMakeFiles/Makefile2:7077: crypto/CMakeFiles/fift.dir/rule] Error 2
make: *** [Makefile:1882: fift] Error 2
```

Ubuntu 22.04 LTS

**Comment by bviktor** [comment]
Indeed. Please fix.

**Comment by awesome-doge** [comment]
The rocksdb problem should now be gone.
What needs to be fixed now is third-party/abseil-cpp/
I have passed the test.

```
# Install dependent packages
apt-get update
apt-get install git build-essential git make cmake clang libgflags-dev zlib1g-dev libssl-dev libreadline-dev libmicrohttpd-dev pkg-config libgsl-dev python3 python3-dev python3-pip -y

# generate env folder / clone ton source code
mkdir ~/ton-env
cd ~/ton-env
git clone --recursive https://github.com/ton-blockchain/ton.git

cd ~/ton-env/ton/third-party/abseil-cpp/
git checkout 20211102.0

# compile
cd ~/ton-env/
mkdir ton-bin
cd ~/ton-env/ton-bin
export CC=$(which clang)
export CXX=$(which clang++)
export CCACHE_DISABLE=1
cmake ~/ton-env/ton -DCMAKE_BUILD_TYPE=Release -Wno-dev

make -j 4
```

https://github.com/ton-blockchain/ton/pull/392

**Comment by awesome-doge** [comment]
* I think the issue with compilation has been resolved.
* The next problem will be that mytonctrl doesn't work properly on ubuntu 22.04.

<img width="1512" alt="截圖 2022-10-08 21 43 36" src="https://user-images.githubusercontent.com/54278075/194710590-7d8f488b-cbb8-4d27-95c7-a011bf52edf1.png">

**Comment by Suhar777777** [comment]
> * I think the issue with compilation has been resolved.
> * The next problem will be that mytonctrl doesn't work properly on ubuntu 22.04.
>   
>   * It looks like the main problem is on OS ubuntu 22.04 and python 3.10.x.
> 
> The current error code is as follows
> 
> ```
> Error: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
> ```
> 
> <img alt="截圖 2022-10-08 21 43 36" width="1512" src="https://user-images.githubusercontent.com/54278075/194710590-7d8f488b-cbb8-4d27-95c7-a011bf52edf1.png">

Update CRC16

**Comment by awesome-doge** [comment]
> CRC

Can you tell me what to do in more detail?

**Comment by sonofmom** [comment]
@awesome-doge, here is the fix:

https://github.com/ton-blockchain/mytonctrl/pull/114

**Comment by igroman787** [comment]
this issue is fixed by commit: https://github.com/ton-blockchain/mytonctrl/pull/114
