### ISSUE TITLE
Compiler replacement with `ninja`

### ISSUE THREAD

**Issue by awesome-doge** [ton-blockchain/mytonctrl#99]
Goal: Replace `cmake` or `make` build commands with `ninja`.

According to @neodiX42 there is a better way to compile, called `ninja`. So I conducted a test, and the following are the results of the experiment.

|           | cmake-ninja-Precompiled(s) | cmake-Precompiled(s) | ninja-compiled(s) | make-compiled(s) | performance improvement |
|-----------|----------------------------|----------------------|-------------------|------------------|-------------------------|
| m1-max(1) | 5                          | 6                    | 147               | 165              |                         |
| m1-max(2) | 5                          | 6                    | 148               | 164              |                         |
| m1-max(3) | 6                          | 6                    | 149               | 164              |                         |
| m1-max(4) | 6                          | 6                    | 147               | 161              |                         |
| average   | 5.5                        | 6                    | 147.75            | 163.5            | 10%                     |
|           |                            |                      |                   |                  |                         |
| 3990x(1)  | 3                          | 3                    | 69                | 116              |                         |
| 3990x(2)  | 2                          | 3                    | 70                | 115              |                         |
| 3990x(3)  | 3                          | 3                    | 68                | 115              |                         |
| 3990x(4)  | 3                          | 4                    | 69                | 116              |                         |
| average   | 2.75                       | 3.25                 | 69                | 115.5            | 40%                     |

I'll start trying to replace the `mytonctrl` build process with `ninja` and commit.

**Comment by igroman787** [comment]
Merged
